light_color_list:
  - '255, 109, 0'
  - '255, 115, 0'
  - '255, 121, 0'
  - '255, 126, 0'
  - '255, 131, 0'
  - '255, 137, 18'
  - '255, 142, 33'
  - '255, 147, 44'
  - '255, 152, 54'
  - '255, 157, 63'
  - '255, 161, 72'
  - '255, 165, 79'
  - '255, 169, 87'
  - '255, 173, 94'
  - '255, 177, 101'
  - '255, 180, 107'
  - '255, 184, 114'
  - '255, 187, 120'
  - '255, 190, 126'
  - '255, 193, 132'
  - '255, 196, 137'
  - '255, 199, 143'
  - '255, 201, 148'
  - '255, 204, 153'
  - '255, 206, 159'
  - '255, 209, 163'
  - '255, 211, 168'
  - '255, 213, 173'
  - '255, 215, 177'
  - '255, 217, 182'
  - '255, 219, 186'
  - '255, 221, 190'
  - '255, 223, 194'
  - '255, 225, 198'
  - '255, 227, 202'
  - '255, 228, 206'
  - '255, 230, 210'
  - '255, 232, 213'
  - '255, 233, 217'
  - '255, 235, 220'
geocode:
  - lat: -1.997179
  - lng: -54.861552